server:
  port: 8080

spring:
  profiles:
    active: druid
  redis:
    database: 0
    host: 122.51.222.39
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smile.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl