server:
  port: 8080

spring:
  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/spring_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      userName: root
      password: 123456
    slaver:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/spring_test2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      userName: root
      password: 123456

mybatis:
  type-aliases-package: com.smile.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl